### ISSUE TITLE
How to obtain the data?

### ISSUE THREAD

**Issue by sebastianpinedaar** [ihsanullah2131/meta-album#2]
Hi!

I am trying to get the data, but when I use the reference code, I just obtain a dataframe with the images names.

More specifically, I am running:

```python
dataset = openml.datasets.get_dataset(44241)

X, y, categorical_indicator, attribute_names = dataset.get_data(
    dataset_format="dataframe", target=dataset.default_target_attribute
)
```

And I obtain something like this:
![image](https://user-images.githubusercontent.com/7019987/216348488-b8bd41cd-9165-48f5-ba56-3ab2451173ba.png)

How can I obtain the images and labels in the data format suggested [here](https://github.com/ihsaan-ullah/meta-album/tree/master/DataFormat)?

Thanks in advance.

**Comment by ihsaan-ullah** [comment]
Hi,

Meta-Album datasets are in this format : https://github.com/ihsaan-ullah/meta-album/tree/master/DataFormat

Please use the following code to download the complete dataset:
```python
import openml

dataset = openml.datasets.get_dataset(44241, download_data=True, download_all_files=True)
```

This dataset will be downloaded in openml cache directory. You can check it with this code:
```python
print(openml.config.cache_directory)
```

**Comment by sebastianpinedaar** [comment]
Thanks, it actually worked!
I had to update to `openml=0.13.0` otherwise it does not work (I was using `openml=0.12.2`).
