### ISSUE TITLE
Possibly wrong dataset ID

### ISSUE THREAD

**Issue by sebastianpinedaar** [ihsanullah2131/meta-album#3]
Hi!

I was downloading the data for Set-1 (second split) from [HERE](https://meta-album.github.io/) but I notice that the dataset PLT.PLT_NET  has the same ID as PLT.FLW from the Set-0, namely 44239. Is this intended?

Best,

Sebastian

**Comment by ihsaan-ullah** [comment]
Thank you for pointing to the mistake. The link to PLT_NET detail page was wrong. It is now fixed and points to the right details page.

FLW : https://meta-album.github.io/datasets/FLW.html
PLT_NET : https://meta-album.github.io/datasets/PLT_NET.html

**Comment by sebastianpinedaar** [comment]
Thanks!
