### ISSUE TITLE
No OCR dataset for extended version

### ISSUE THREAD

**Issue by sebastianpinedaar** [ihsanullah2131/meta-album#4]
Hi!

I noticed that the OCR datasets do not have an associated OpenML dataset ID in the extended version, [like here](https://meta-album.github.io/datasets/MD_MIX.html). Or am I missing something?

Thanks in advance!

Best,

Sebastian

**Comment by ihsaan-ullah** [comment]
Hi Sabestian,

You are right, we do not have extended versions for OCR datasets. We have a software for the OCR data generation which can be used for generating a bigger dataset.

OmniPrint Generator: https://github.com/SunHaozhe/OmniPrint

I hope this helps.
