### ISSUE TITLE
Exact train/val/test splits for Set0 Set1 Set2

### ISSUE THREAD

**Issue by peustr** [ihsanullah2131/meta-album#5]
Hello and thank you for providing this excellent dataset.

I am not sure if this information exists somewhere and I missed it, but would you please provide the exact splits that reproduce the results in Fig.2 of the paper? If I am not mistaken the code available at the moment concerns only Set0.
[->[permalink to current code]](https://github.com/ihsaan-ullah/meta-album/blob/03d73de3e1f4868d0aac7a110527efd778479614/Code/Scripts/cross_domain_few_shot_learning.sh#L20)

Many thanks.

**Comment by DustinCarrion** [comment]
Hi,

Thank you for your interest in Meta-Album. We have updated the cross-domain few-shot learning script to include the splits used on our paper because, as you mentioned, the previous script only included Set0.

Please do not hesitate to create another issue if you need any extra information.
