### ISSUE TITLE
How to download the datasets?

### ISSUE THREAD

**Issue by zhangbq-research** [ihsanullah2131/meta-album#6]
Hello, I attempt to download the dataset by following  OpenML python API, but I get some issues. Can you help address these issues?
This is our download codes for dataset "LR_AM.DOG":
    # import openml
    1. import openml
    # download dataset with DATASET_ID. Check Dataset detail page for DATASET_ID
    2. dataset = openml.datasets.get_dataset("DOG", download_data=True, download_all_files=True)

When I perform the second line code, there is a issue as follows:

   RuntimeError: No active datasets exist with name DOG

How can  I solve it?

**Comment by ihsaan-ullah** [comment]
Hi, Thank you for using Meta-Album.

the DATASET_ID is a numeric id mentioned on the dataset page: https://meta-album.github.io/datasets/DOG.html

Each dataset has 3 versions, each version with its own id. Below is a screenshot for the DOG dataset page which shows ids for the three versions of this dataset.

<img width="834" alt="Screenshot 2023-03-06 at 9 11 57 PM" src="https://user-images.githubusercontent.com/13259262/223166953-b6d5590d-e504-4823-a3f4-fee824cf321c.png">

so the code should look like this:

```
 dataset = openml.datasets.get_dataset(44313, download_data=True, download_all_files=True)
```

I hope this helps you in solving the issue.

**Comment by ihsaan-ullah** [comment]
This other issue may also be helpful if you are using a different version of OpenML
https://github.com/ihsaan-ullah/meta-album/issues/2

**Comment by zhangbq-research** [comment]
Thank you very much for your help. I attempt to solve the issue but find a new issue.

>>> dataset = openml.datasets.get_dataset(44298, download_data=True, download_all_files=True)
/home/ices806/anaconda3/envs/py36_torch16/lib/python3.6/site-packages/openml/datasets/functions.py:405: UserWarning: ``download_all_files`` is experimental and is likely to break with new releases.
  "``download_all_files`` is experimental and is likely to break with new releases."
/home/ices806/anaconda3/envs/py36_torch16/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/x509.py:17: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  utils.DeprecatedIn35,
WARNING:root:Received uncompressed content from OpenML for https://api.openml.org/data/v1/download/22110998/Meta_Album_DOG_Mini.arff.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ices806/anaconda3/envs/py36_torch16/lib/python3.6/site-packages/openml/datasets/functions.py", line 450, in get_dataset
    description, download_all_files=download_all_files
  File "/home/ices806/anaconda3/envs/py36_torch16/lib/python3.6/site-packages/openml/datasets/functions.py", line 1041, in _get_dataset_parquet
    openml._api_calls._download_minio_bucket(source=cast(str, url), destination=cache_directory)
  File "/home/ices806/anaconda3/envs/py36_torch16/lib/python3.6/site-packages/openml/_api_calls.py", line 191, in _download_minio_bucket
    exists_ok=True,
  File "/home/ices806/anaconda3/envs/py36_torch16/lib/python3.6/site-packages/openml/_api_calls.py", line 138, in _download_minio_file
    proxy = resolve_env_proxies(parsed_url.geturl())
  File "/home/ices806/anaconda3/envs/py36_torch16/lib/python3.6/site-packages/openml/_api_calls.py", line 44, in resolve_env_proxies
    resolved_proxies = requests.utils.get_environ_proxies(url)
TypeError: get_environ_proxies() missing 1 required positional argument: 'no_proxy'

**Comment by ihsaan-ullah** [comment]
Please use OpenML version `0.13.0`

**Comment by zhangbq-research** [comment]
OK, Thank you very much!



---- Replied Message ----
| From | Ihsan ***@***.***> |
| Date | 03/07/2023 15:18 |
| To | ***@***.***> |
| Cc | Zhang Bao ***@***.***>***@***.***> |
| Subject | Re: [ihsaan-ullah/meta-album] How to download the datasets? (Issue #6) |

Please use OpenML version 0.13.0
