### ISSUE TITLE
Dataset Normalization

### ISSUE THREAD

**Issue by HamedHemati** [ihsanullah2131/meta-album#7]
Thanks for the amazing work!

I have a question regarding the mean and std used for normalizing dataset images:

```python
mean=[0.485, 0.456, 0.406]
std=[0.229, 0.224, 0.225]
```

How are the mean and std calculated?
If they are computed using all datasets together, have you analyzed how much it affects the model's performance compared to  per-dataset means and stds when training on individual datasets?

Thanks!

**Comment by ihsaan-ullah** [comment]
Hi @HamedHemati 

We have used imageNet `mean` and `std`.

This can be helpful: https://stackoverflow.com/a/58151903
