### ISSUE TITLE
can't download extend version of some data sets

### ISSUE THREAD

**Issue by ruili-pml** [ihsanullah2131/meta-album#8]
Hi,

Thank you for collecting and processing all these data sets. I tried to download the extend version of some data sets but the ones downloaded from openml didn't contain any real data. The data sets I tried to download are: 44336 (PLT_DOC), 44342 (PRT) and 44341 (RSD). I looked into the closed issues and changed openml into 0.13.0, but it still didn't work. Would be great if you could take a look, thank you.

Kind regards,
Rui

**Comment by ihsaan-ullah** [comment]
Hi @ruili-pml, We are working on it and will notify you as soon as the datasets are available

**Comment by ihsaan-ullah** [comment]
All datasets are now restored and are accessible
