### ISSUE TITLE
Train_test split

### ISSUE THREAD

**Issue by sorobedio** [ihsanullah2131/meta-album#9]
Are there train/test splits or not.
If yes: How to get the train test split for supervise classification? i only found a single folder with images after downloaded.
If not: could you explain briefly how to use in supervised fine-tuning.
Thank you

**Comment by ihsaan-ullah** [comment]
There are no pre-defined train/test splits. These datasets are designed for few-shot learning and can be split in many ways e.g. 5-way-10-shot etc.

For supervised fine-tuning you can split it by 50/50 (train/test).
